-- Seed all 65 supported languages with proper metadata
INSERT INTO public.supported_languages (locale, name, native_name, is_rtl, is_active, tier, translation_progress)
VALUES
  -- Tier 1: Base languages (static files)
  ('es', 'Spanish', 'Español', false, true, 1, 100),
  ('en', 'English', 'English', false, true, 1, 100),
  ('ca', 'Catalan', 'Català', false, true, 1, 100),
  ('fr', 'French', 'Français', false, true, 1, 100),
  
  -- Tier 2: Major European & Global
  ('de', 'German', 'Deutsch', false, true, 2, 0),
  ('pt', 'Portuguese', 'Português', false, true, 2, 0),
  ('pt-BR', 'Portuguese (Brazil)', 'Português (Brasil)', false, true, 2, 0),
  ('it', 'Italian', 'Italiano', false, true, 2, 0),
  ('nl', 'Dutch', 'Nederlands', false, true, 2, 0),
  ('pl', 'Polish', 'Polski', false, true, 2, 0),
  ('ru', 'Russian', 'Русский', false, true, 2, 0),
  ('zh-CN', 'Chinese (Simplified)', '简体中文', false, true, 2, 0),
  ('zh-TW', 'Chinese (Traditional)', '繁體中文', false, true, 2, 0),
  ('ja', 'Japanese', '日本語', false, true, 2, 0),
  ('ko', 'Korean', '한국어', false, true, 2, 0),
  ('ar', 'Arabic', 'العربية', true, true, 2, 0),
  
  -- Tier 3: Secondary European & Asian
  ('cs', 'Czech', 'Čeština', false, true, 3, 0),
  ('ro', 'Romanian', 'Română', false, true, 3, 0),
  ('hu', 'Hungarian', 'Magyar', false, true, 3, 0),
  ('sv', 'Swedish', 'Svenska', false, true, 3, 0),
  ('da', 'Danish', 'Dansk', false, true, 3, 0),
  ('no', 'Norwegian', 'Norsk', false, true, 3, 0),
  ('fi', 'Finnish', 'Suomi', false, true, 3, 0),
  ('el', 'Greek', 'Ελληνικά', false, true, 3, 0),
  ('tr', 'Turkish', 'Türkçe', false, true, 3, 0),
  ('uk', 'Ukrainian', 'Українська', false, true, 3, 0),
  ('he', 'Hebrew', 'עברית', true, true, 3, 0),
  ('th', 'Thai', 'ไทย', false, true, 3, 0),
  ('vi', 'Vietnamese', 'Tiếng Việt', false, true, 3, 0),
  ('id', 'Indonesian', 'Bahasa Indonesia', false, true, 3, 0),
  ('ms', 'Malay', 'Bahasa Melayu', false, true, 3, 0),
  ('hi', 'Hindi', 'हिन्दी', false, true, 3, 0),
  ('bn', 'Bengali', 'বাংলা', false, true, 3, 0),
  ('tl', 'Tagalog', 'Tagalog', false, true, 3, 0),
  
  -- Tier 4: Extended coverage
  ('ur', 'Urdu', 'اردو', true, true, 4, 0),
  ('fa', 'Persian', 'فارسی', true, true, 4, 0),
  ('bg', 'Bulgarian', 'Български', false, true, 4, 0),
  ('hr', 'Croatian', 'Hrvatski', false, true, 4, 0),
  ('sk', 'Slovak', 'Slovenčina', false, true, 4, 0),
  ('sl', 'Slovenian', 'Slovenščina', false, true, 4, 0),
  ('et', 'Estonian', 'Eesti', false, true, 4, 0),
  ('lv', 'Latvian', 'Latviešu', false, true, 4, 0),
  ('lt', 'Lithuanian', 'Lietuvių', false, true, 4, 0),
  ('es-MX', 'Spanish (Mexico)', 'Español (México)', false, true, 4, 0),
  ('es-AR', 'Spanish (Argentina)', 'Español (Argentina)', false, true, 4, 0),
  ('en-US', 'English (US)', 'English (US)', false, true, 4, 0),
  ('fr-CA', 'French (Canada)', 'Français (Canada)', false, true, 4, 0),
  ('af', 'Afrikaans', 'Afrikaans', false, true, 4, 0),
  ('ga', 'Irish', 'Gaeilge', false, true, 4, 0),
  ('is', 'Icelandic', 'Íslenska', false, true, 4, 0),
  ('mt', 'Maltese', 'Malti', false, true, 4, 0),
  ('lb', 'Luxembourgish', 'Lëtzebuergesch', false, true, 4, 0),
  ('bs', 'Bosnian', 'Bosanski', false, true, 4, 0),
  ('sr', 'Serbian', 'Српски', false, true, 4, 0),
  ('mk', 'Macedonian', 'Македонски', false, true, 4, 0),
  ('sq', 'Albanian', 'Shqip', false, true, 4, 0),
  ('ka', 'Georgian', 'ქართული', false, true, 4, 0),
  ('hy', 'Armenian', 'Հայերdelays', false, true, 4, 0),
  ('az', 'Azerbaijani', 'Azərbaycan', false, true, 4, 0),
  ('kk', 'Kazakh', 'Қазақ', false, true, 4, 0),
  ('uz', 'Uzbek', 'Oʻzbek', false, true, 4, 0),
  ('ne', 'Nepali', 'नेपाली', false, true, 4, 0),
  ('si', 'Sinhala', 'සිංහල', false, true, 4, 0),
  ('my', 'Burmese', 'မြန်မာ', false, true, 4, 0),
  ('km', 'Khmer', 'ខ្មែរ', false, true, 4, 0),
  ('lo', 'Lao', 'ລາວ', false, true, 4, 0),
  ('am', 'Amharic', 'አማርኛ', false, true, 4, 0),
  ('sw', 'Swahili', 'Kiswahili', false, true, 4, 0),
  ('ha', 'Hausa', 'Hausa', false, true, 4, 0),
  ('yo', 'Yoruba', 'Yorùbá', false, true, 4, 0),
  ('ig', 'Igbo', 'Igbo', false, true, 4, 0)
ON CONFLICT (locale) DO UPDATE SET
  name = EXCLUDED.name,
  native_name = EXCLUDED.native_name,
  is_rtl = EXCLUDED.is_rtl,
  tier = EXCLUDED.tier,
  is_active = EXCLUDED.is_active;